[package]
name = "playit-cli"
version = "1.0.0-rc2"
edition = "2021"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
playit-agent-core = { path = "../agent_core" }
playit-agent-proto = { path = "../agent_proto" }
clap = { version = "4.0.10", features = ["derive"] }
rand = "0.8.5"
hex = "0.4.3"
anyhow = "1.0"
urlencoding = "2.1.2"
serde_json = "1"
toml = "0.5.9"
serde_yaml = "0.9.14"
serde = { version = "1", features = ["derive"] }
uuid = "1.1.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[package.metadata.bundle]
# FIXME: This is the minimum configuration. Add or change stuff as needed.
identifier = "com.playit.cli"
icon = ["../../assets/playit@2x.png"]
linux_use_terminal = true
