name: Release

on:
    # release:
    #     types: [published]
    push:

jobs:
    build:
        runs-on: ${{ matrix.target.os }}
        environment: production
        strategy:
            fail-fast: false
            matrix:
                target:
                    - target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest
                    - target: i686-unknown-linux-gnu
                      os: ubuntu-latest
                      prebuild: sudo apt-get install -y gcc-multilib
                    - target: aarch64-unknown-linux-gnu
                      os: ubuntu-latest
                      prebuild: sudo apt-get install -y gcc-aarch64-linux-gnu
                    - target: armv7-unknown-linux-gnueabihf
                      os: ubuntu-latest
                      prebuild: sudo apt-get install -y gcc-arm-linux-gnueabihf

                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
                    - target: i686-pc-windows-msvc
                      os: windows-latest
                    # https://github.com/briansmith/ring/issues/1167
                    # - target: aarch64-pc-windows-msvc
                    #   os: windows-latest

                    # TODO: Automate bundling of macOS binaries
                    - target: x86_64-apple-darwin
                      os: macos-latest
                    - target: aarch64-apple-darwin
                      os: macos-latest

        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target.target }}

            - name: Run Prebuild Commands
              if: ${{ matrix.target.prebuild }}
              run: ${{ matrix.target.prebuild }}

            - name: Build
              run: cargo build --release --target ${{ matrix.target.target }} --locked

            - name: Get Release Data
              id: data
              run: |
                  cargo install tomato-toml
                  which tomato
                  bin=$(tomato get package.name packages/agent_cli/Cargo.toml)
                  echo "$bin"
                  ext=$([[ ${{ matrix.target.target }} =~ "windows" ]] && echo ".exe")
                  echo "$ext"
                  echo "BIN=$bin$ext" >> $GITHUB_OUTPUT
              shell: bash

            # - name: Upload Release
            #   uses: AButler/upload-release-assets@v2.0
            #   with:
            #       files: "target/${{ matrix.target.target }}/release/${{ steps.data.outputs.BIN }}"
            #       repo-token: ${{ secrets.GITHUB_TOKEN }}
            #       release-tag: ${{ github.ref }}
